### ISSUE TITLE
Add an ability to specify openssl version

### ISSUE THREAD

**Issue by ildar-aim** [fpoirotte/phpfarm#23]
I have 2 openssl packages

```
core/openssl 1.1.0.h-1
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
core/openssl-1.0 1.0.2.o-1
    The Open Source toolkit for Secure Sockets Layer and Transport Layer Security
```

I cannot compile php5.6.36 due to this error

```
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘openssl_x509v3_subjectAltName’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:1904:15: error: dereferencing pointer to incomplete type ‘X509_EXTENSION’ {aka ‘struct X509_extension_st’}
  p = extension->value->data;
               ^~
```

or php5.3.29

```
/opt/phpfarm_new/src/php-5.3.29/ext/openssl/openssl.c: In function ‘openssl_x509v3_subjectAltName’:
/opt/phpfarm_new/src/php-5.3.29/ext/openssl/openssl.c:1355:15: error: dereferencing pointer to incomplete type ‘X509_EXTENSION’ {aka ‘struct X509_extension_st’}
```

<details>
 <summary>Full error log</summary>

```
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘add_assoc_name_entry’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:664:4: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
    to_add = ASN1_STRING_data(str);
    ^~~~~~
In file included from /usr/include/openssl/bn.h:31,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:44:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘asn1_time_to_time_t’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:717:2: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
  if (ASN1_STRING_length(timestr) != strlen((const char*)ASN1_STRING_data(timestr))) {
  ^~
In file included from /usr/include/openssl/bn.h:31,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:44:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:732:2: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
  strbuf = estrdup((char *)ASN1_STRING_data(timestr));
  ^~~~~~
In file included from /usr/include/openssl/bn.h:31,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:44:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘php_openssl_get_evp_md_from_algo’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:1057:24: warning: implicit declaration of function ‘EVP_dss1’; did you mean ‘EVP_sha1’? [-Wimplicit-function-declaration]
    mdtype = (EVP_MD *) EVP_dss1();
                        ^~~~~~~~
                        EVP_sha1
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:1057:13: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
    mdtype = (EVP_MD *) EVP_dss1();
             ^
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘zif_openssl_spki_export_challenge’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:1726:2: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
  RETVAL_STRING((char *) ASN1_STRING_data(spki->spkac->challenge), 1);
  ^~~~~~~~~~~~~
In file included from /usr/include/openssl/bn.h:31,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:44:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘openssl_x509v3_subjectAltName’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:1904:15: error: dereferencing pointer to incomplete type ‘X509_EXTENSION’ {aka ‘struct X509_extension_st’}
  p = extension->value->data;
               ^~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:1925:6: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
      BIO_write(bio, ASN1_STRING_data(as),
      ^~~~~~~~~
In file included from /usr/include/openssl/bn.h:31,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:44:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:1931:6: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
      BIO_write(bio, ASN1_STRING_data(as),
      ^~~~~~~~~
In file included from /usr/include/openssl/bn.h:31,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:44:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:1937:6: warning: ‘ASN1_STRING_data’ is deprecated [-Wdeprecated-declarations]
      BIO_write(bio, ASN1_STRING_data(as),
      ^~~~~~~~~
In file included from /usr/include/openssl/bn.h:31,
                 from /usr/include/openssl/asn1.h:24,
                 from /usr/include/openssl/objects.h:916,
                 from /usr/include/openssl/evp.h:27,
                 from /opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:44:
/usr/include/openssl/asn1.h:553:1: note: declared here
 DEPRECATEDIN_1_1_0(unsigned char *ASN1_STRING_data(ASN1_STRING *x))
 ^~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘zif_openssl_x509_parse’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:1982:10: error: dereferencing pointer to incomplete type ‘X509’ {aka ‘struct x509_st’}
  if (cert->name) {
          ^~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘php_openssl_generate_private_key’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:3420:5: warning: ‘RSA_generate_key’ is deprecated [-Wdeprecated-declarations]
     if (EVP_PKEY_assign_RSA(req->priv_key, RSA_generate_key(req->priv_key_bits, 0x10001, NULL, NULL))) {
     ^~
In file included from /usr/include/openssl/rsa.h:13,
                 from /usr/include/openssl/x509.h:31,
                 from /opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:45:
/usr/include/openssl/rsa.h:193:1: note: declared here
 DEPRECATEDIN_0_9_8(RSA *RSA_generate_key(int bits, unsigned long e, void
 ^~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:3428:6: warning: ‘DSA_generate_parameters’ is deprecated [-Wdeprecated-declarations]
      DSA *dsapar = DSA_generate_parameters(req->priv_key_bits, NULL, 0, NULL, NULL, NULL, NULL);
      ^~~
In file included from /usr/include/openssl/dh.h:13,
                 from /usr/include/openssl/dsa.h:31,
                 from /usr/include/openssl/x509.h:32,
                 from /opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:45:
/usr/include/openssl/dsa.h:122:1: note: declared here
 DEPRECATEDIN_0_9_8(DSA *DSA_generate_parameters(int bits,
 ^~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:3446:6: warning: ‘DH_generate_parameters’ is deprecated [-Wdeprecated-declarations]
      DH *dhpar = DH_generate_parameters(req->priv_key_bits, 2, NULL, NULL);
      ^~
In file included from /usr/include/openssl/dh.h:13,
                 from /usr/include/openssl/dsa.h:31,
                 from /usr/include/openssl/x509.h:32,
                 from /opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:45:
/usr/include/openssl/dh.h:135:1: note: declared here
 DEPRECATEDIN_0_9_8(DH *DH_generate_parameters(int prime_len, int generator,
 ^~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘php_openssl_is_private_key’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:3485:14: error: dereferencing pointer to incomplete type ‘EVP_PKEY’ {aka ‘struct evp_pkey_st’}
  switch (pkey->type) {
              ^~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘php_openssl_pkey_init_dsa’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:3557:10: error: dereferencing pointer to incomplete type ‘DSA’ {aka ‘struct dsa_st’}
  if (!dsa->p || !dsa->q || !dsa->g) {
          ^~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘php_openssl_pkey_init_dh’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:3580:9: error: dereferencing pointer to incomplete type ‘DH’ {aka ‘struct dh_st’}
  if (!dh->p || !dh->g) {
         ^~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘zif_openssl_pkey_new’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:3548:9: error: dereferencing pointer to incomplete type ‘RSA’ {aka ‘struct rsa_st’}
    _type->_name = BN_bin2bn(         \
         ^~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:3617:6: note: in expansion of macro ‘OPENSSL_PKEY_SET_BN’
      OPENSSL_PKEY_SET_BN(Z_ARRVAL_PP(data), rsa, n);
      ^~~~~~~~~~~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘zif_openssl_sign’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:4801:13: error: storage size of ‘md_ctx’ isn’t known
  EVP_MD_CTX md_ctx;
             ^~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:4845:2: warning: implicit declaration of function ‘EVP_MD_CTX_cleanup’; did you mean ‘EVP_MD_CTX_create’? [-Wimplicit-function-declaration]
  EVP_MD_CTX_cleanup(&md_ctx);
  ^~~~~~~~~~~~~~~~~~
  EVP_MD_CTX_create
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:4801:13: warning: unused variable ‘md_ctx’ [-Wunused-variable]
  EVP_MD_CTX md_ctx;
             ^~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘zif_openssl_verify’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:4859:17: error: storage size of ‘md_ctx’ isn’t known
  EVP_MD_CTX     md_ctx;
                 ^~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:4859:17: warning: unused variable ‘md_ctx’ [-Wunused-variable]
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘zif_openssl_seal’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:4920:17: error: storage size of ‘ctx’ isn’t known
  EVP_CIPHER_CTX ctx;
                 ^~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:4920:17: warning: unused variable ‘ctx’ [-Wunused-variable]
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘zif_openssl_open’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:5048:17: error: storage size of ‘ctx’ isn’t known
  EVP_CIPHER_CTX ctx;
                 ^~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:5048:17: warning: unused variable ‘ctx’ [-Wunused-variable]
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘zif_openssl_digest’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:5154:13: error: storage size of ‘md_ctx’ isn’t known
  EVP_MD_CTX md_ctx;
             ^~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:5154:13: warning: unused variable ‘md_ctx’ [-Wunused-variable]
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘zif_openssl_encrypt’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:5233:17: error: storage size of ‘cipher_ctx’ isn’t known
  EVP_CIPHER_CTX cipher_ctx;
                 ^~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:5233:17: warning: unused variable ‘cipher_ctx’ [-Wunused-variable]
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c: In function ‘zif_openssl_decrypt’:
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:5316:17: error: storage size of ‘cipher_ctx’ isn’t known
  EVP_CIPHER_CTX cipher_ctx;
                 ^~~~~~~~~~
/opt/phpfarm_new/src/php-5.6.36/ext/openssl/openssl.c:5316:17: warning: unused variable ‘cipher_ctx’ [-Wunused-variable]
make: *** [Makefile:592: ext/openssl/openssl.lo] Error 1
make failed.
An error occurred while trying to install PHP 5.6.36.
```

</details>

It seems it tries to link the new openssl 1.1.0 version which is default.

How can I configure phpfarm to compile using the old openssl 1.0 ?

I tried this with no luck

https://stackoverflow.com/questions/27095616/how-to-compile-php-5-5-19-with-openssl-1-0-1-on-os-x?rq=1

<details>
<summary>openssl-1.0 files</summary>

```
openssl-1.0 /usr/
openssl-1.0 /usr/bin/
openssl-1.0 /usr/bin/openssl-1.0
openssl-1.0 /usr/include/
openssl-1.0 /usr/include/openssl-1.0/
openssl-1.0 /usr/include/openssl-1.0/openssl/
openssl-1.0 /usr/include/openssl-1.0/openssl/aes.h
openssl-1.0 /usr/include/openssl-1.0/openssl/asn1.h
openssl-1.0 /usr/include/openssl-1.0/openssl/asn1_mac.h
openssl-1.0 /usr/include/openssl-1.0/openssl/asn1t.h
openssl-1.0 /usr/include/openssl-1.0/openssl/bio.h
openssl-1.0 /usr/include/openssl-1.0/openssl/blowfish.h
openssl-1.0 /usr/include/openssl-1.0/openssl/bn.h
openssl-1.0 /usr/include/openssl-1.0/openssl/buffer.h
openssl-1.0 /usr/include/openssl-1.0/openssl/camellia.h
openssl-1.0 /usr/include/openssl-1.0/openssl/cast.h
openssl-1.0 /usr/include/openssl-1.0/openssl/cmac.h
openssl-1.0 /usr/include/openssl-1.0/openssl/cms.h
openssl-1.0 /usr/include/openssl-1.0/openssl/comp.h
openssl-1.0 /usr/include/openssl-1.0/openssl/conf.h
openssl-1.0 /usr/include/openssl-1.0/openssl/conf_api.h
openssl-1.0 /usr/include/openssl-1.0/openssl/crypto.h
openssl-1.0 /usr/include/openssl-1.0/openssl/des.h
openssl-1.0 /usr/include/openssl-1.0/openssl/des_old.h
openssl-1.0 /usr/include/openssl-1.0/openssl/dh.h
openssl-1.0 /usr/include/openssl-1.0/openssl/dsa.h
openssl-1.0 /usr/include/openssl-1.0/openssl/dso.h
openssl-1.0 /usr/include/openssl-1.0/openssl/dtls1.h
openssl-1.0 /usr/include/openssl-1.0/openssl/e_os2.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ebcdic.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ec.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ecdh.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ecdsa.h
openssl-1.0 /usr/include/openssl-1.0/openssl/engine.h
openssl-1.0 /usr/include/openssl-1.0/openssl/err.h
openssl-1.0 /usr/include/openssl-1.0/openssl/evp.h
openssl-1.0 /usr/include/openssl-1.0/openssl/hmac.h
openssl-1.0 /usr/include/openssl-1.0/openssl/idea.h
openssl-1.0 /usr/include/openssl-1.0/openssl/krb5_asn.h
openssl-1.0 /usr/include/openssl-1.0/openssl/kssl.h
openssl-1.0 /usr/include/openssl-1.0/openssl/lhash.h
openssl-1.0 /usr/include/openssl-1.0/openssl/md4.h
openssl-1.0 /usr/include/openssl-1.0/openssl/md5.h
openssl-1.0 /usr/include/openssl-1.0/openssl/mdc2.h
openssl-1.0 /usr/include/openssl-1.0/openssl/modes.h
openssl-1.0 /usr/include/openssl-1.0/openssl/obj_mac.h
openssl-1.0 /usr/include/openssl-1.0/openssl/objects.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ocsp.h
openssl-1.0 /usr/include/openssl-1.0/openssl/opensslconf.h
openssl-1.0 /usr/include/openssl-1.0/openssl/opensslv.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ossl_typ.h
openssl-1.0 /usr/include/openssl-1.0/openssl/pem.h
openssl-1.0 /usr/include/openssl-1.0/openssl/pem2.h
openssl-1.0 /usr/include/openssl-1.0/openssl/pkcs12.h
openssl-1.0 /usr/include/openssl-1.0/openssl/pkcs7.h
openssl-1.0 /usr/include/openssl-1.0/openssl/pqueue.h
openssl-1.0 /usr/include/openssl-1.0/openssl/rand.h
openssl-1.0 /usr/include/openssl-1.0/openssl/rc2.h
openssl-1.0 /usr/include/openssl-1.0/openssl/rc4.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ripemd.h
openssl-1.0 /usr/include/openssl-1.0/openssl/rsa.h
openssl-1.0 /usr/include/openssl-1.0/openssl/safestack.h
openssl-1.0 /usr/include/openssl-1.0/openssl/seed.h
openssl-1.0 /usr/include/openssl-1.0/openssl/sha.h
openssl-1.0 /usr/include/openssl-1.0/openssl/srp.h
openssl-1.0 /usr/include/openssl-1.0/openssl/srtp.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ssl.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ssl2.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ssl23.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ssl3.h
openssl-1.0 /usr/include/openssl-1.0/openssl/stack.h
openssl-1.0 /usr/include/openssl-1.0/openssl/symhacks.h
openssl-1.0 /usr/include/openssl-1.0/openssl/tls1.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ts.h
openssl-1.0 /usr/include/openssl-1.0/openssl/txt_db.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ui.h
openssl-1.0 /usr/include/openssl-1.0/openssl/ui_compat.h
openssl-1.0 /usr/include/openssl-1.0/openssl/whrlpool.h
openssl-1.0 /usr/include/openssl-1.0/openssl/x509.h
openssl-1.0 /usr/include/openssl-1.0/openssl/x509_vfy.h
openssl-1.0 /usr/include/openssl-1.0/openssl/x509v3.h
openssl-1.0 /usr/lib/
openssl-1.0 /usr/lib/libcrypto.so.1.0.0
openssl-1.0 /usr/lib/libssl.so.1.0.0
openssl-1.0 /usr/lib/openssl-1.0/
openssl-1.0 /usr/lib/openssl-1.0/engines/
openssl-1.0 /usr/lib/openssl-1.0/engines/lib4758cca.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libaep.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libatalla.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libcapi.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libchil.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libcswift.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libgmp.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libgost.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libnuron.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libpadlock.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libsureware.so
openssl-1.0 /usr/lib/openssl-1.0/engines/libubsec.so
openssl-1.0 /usr/lib/openssl-1.0/libcrypto.so
openssl-1.0 /usr/lib/openssl-1.0/libssl.so
openssl-1.0 /usr/lib/openssl-1.0/pkgconfig/
openssl-1.0 /usr/lib/openssl-1.0/pkgconfig/libcrypto.pc
openssl-1.0 /usr/lib/openssl-1.0/pkgconfig/libssl.pc
openssl-1.0 /usr/lib/openssl-1.0/pkgconfig/openssl.pc
openssl-1.0 /usr/share/
openssl-1.0 /usr/share/licenses/
openssl-1.0 /usr/share/licenses/openssl-1.0/
openssl-1.0 /usr/share/licenses/openssl-1.0/LICENSE

```
</details>

<details>
<summary>openssl-1.1 files</summary>

```
openssl /etc/
openssl /etc/ssl/
openssl /etc/ssl/certs/
openssl /etc/ssl/misc/
openssl /etc/ssl/misc/CA.pl
openssl /etc/ssl/misc/tsget
openssl /etc/ssl/openssl.cnf
openssl /etc/ssl/openssl.cnf.dist
openssl /etc/ssl/private/
openssl /usr/
openssl /usr/bin/
openssl /usr/bin/c_rehash
openssl /usr/bin/openssl
openssl /usr/include/
openssl /usr/include/openssl/
openssl /usr/include/openssl/aes.h
openssl /usr/include/openssl/asn1.h
openssl /usr/include/openssl/asn1_mac.h
openssl /usr/include/openssl/asn1t.h
openssl /usr/include/openssl/async.h
openssl /usr/include/openssl/bio.h
openssl /usr/include/openssl/blowfish.h
openssl /usr/include/openssl/bn.h
openssl /usr/include/openssl/buffer.h
openssl /usr/include/openssl/camellia.h
openssl /usr/include/openssl/cast.h
openssl /usr/include/openssl/cmac.h
openssl /usr/include/openssl/cms.h
openssl /usr/include/openssl/comp.h
openssl /usr/include/openssl/conf.h
openssl /usr/include/openssl/conf_api.h
openssl /usr/include/openssl/crypto.h
openssl /usr/include/openssl/ct.h
openssl /usr/include/openssl/des.h
openssl /usr/include/openssl/dh.h
openssl /usr/include/openssl/dsa.h
openssl /usr/include/openssl/dtls1.h
openssl /usr/include/openssl/e_os2.h
openssl /usr/include/openssl/ebcdic.h
openssl /usr/include/openssl/ec.h
openssl /usr/include/openssl/ecdh.h
openssl /usr/include/openssl/ecdsa.h
openssl /usr/include/openssl/engine.h
openssl /usr/include/openssl/err.h
openssl /usr/include/openssl/evp.h
openssl /usr/include/openssl/hmac.h
openssl /usr/include/openssl/idea.h
openssl /usr/include/openssl/kdf.h
openssl /usr/include/openssl/lhash.h
openssl /usr/include/openssl/md2.h
openssl /usr/include/openssl/md4.h
openssl /usr/include/openssl/md5.h
openssl /usr/include/openssl/mdc2.h
openssl /usr/include/openssl/modes.h
openssl /usr/include/openssl/obj_mac.h
openssl /usr/include/openssl/objects.h
openssl /usr/include/openssl/ocsp.h
openssl /usr/include/openssl/opensslconf.h
openssl /usr/include/openssl/opensslv.h
openssl /usr/include/openssl/ossl_typ.h
openssl /usr/include/openssl/pem.h
openssl /usr/include/openssl/pem2.h
openssl /usr/include/openssl/pkcs12.h
openssl /usr/include/openssl/pkcs7.h
openssl /usr/include/openssl/rand.h
openssl /usr/include/openssl/rc2.h
openssl /usr/include/openssl/rc4.h
openssl /usr/include/openssl/rc5.h
openssl /usr/include/openssl/ripemd.h
openssl /usr/include/openssl/rsa.h
openssl /usr/include/openssl/safestack.h
openssl /usr/include/openssl/seed.h
openssl /usr/include/openssl/sha.h
openssl /usr/include/openssl/srp.h
openssl /usr/include/openssl/srtp.h
openssl /usr/include/openssl/ssl.h
openssl /usr/include/openssl/ssl2.h
openssl /usr/include/openssl/ssl3.h
openssl /usr/include/openssl/stack.h
openssl /usr/include/openssl/symhacks.h
openssl /usr/include/openssl/tls1.h
openssl /usr/include/openssl/ts.h
openssl /usr/include/openssl/txt_db.h
openssl /usr/include/openssl/ui.h
openssl /usr/include/openssl/whrlpool.h
openssl /usr/include/openssl/x509.h
openssl /usr/include/openssl/x509_vfy.h
openssl /usr/include/openssl/x509v3.h
openssl /usr/lib/
openssl /usr/lib/engines-1.1/
openssl /usr/lib/engines-1.1/afalg.so
openssl /usr/lib/engines-1.1/capi.so
openssl /usr/lib/engines-1.1/padlock.so
openssl /usr/lib/libcrypto.so
openssl /usr/lib/libcrypto.so.1.1
openssl /usr/lib/libssl.so
openssl /usr/lib/libssl.so.1.1
openssl /usr/lib/pkgconfig/
openssl /usr/lib/pkgconfig/libcrypto.pc
openssl /usr/lib/pkgconfig/libssl.pc
openssl /usr/lib/pkgconfig/openssl.pc
openssl /usr/share/
openssl /usr/share/licenses/
openssl /usr/share/licenses/openssl/
openssl /usr/share/licenses/openssl/LICENSE

```
</details>

**Comment by fpoirotte** [comment]
PHP expects the following file hierarchy for OpenSSL:
* @basedir@/include/openssl/ for header files
* @basedir@/lib/ for library files
where @basedir@ is usually one of /usr or /usrlocal/
It does not support arbitrary hierarchies like <basedir>/include/openssl-@version@/openssl and so on.

That being said, PHP **does support using pkg-config** to find the information it needs about OpenSSL's installation, and it happens that pkg-config can be instructed to look for .pc files in a non-standard directory using the ``PKG_CONFIG_PATH`` environment variable.

So, assuming pkg-config is installed on your system, you could try something like this:
```
me@pc:~/phpfarm/src$ PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig/
me@pc:~/phpfarm/src$ export PKG_CONFIG_PATH
me@pc:~/phpfarm/src$ ./main 5.6.36
```

**Comment by ildar-aim** [comment]
Thank you very much!

I have managed to compile 5.6.36 / 5.3.29 versions with a minor issue.
There is different openssl versions on the phpinfo page.

![img](https://i.imgur.com/IyWn0Sx.png)

![img2](https://i.imgur.com/Th3jBBW.png)

Everthing else works correctly.

I suppose it should be in your wiki.
